version: "3.9"

services:
  web:
    build: .
    container_name: fuel_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
    
    entrypoint: ["/entrypoint.sh"]

  redis:
    image: redis:7-alpine
    container_name: fuel_redis
    restart: always
