version: "3.9"

services:
  web:
    build: .
    container_name: fuel_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
    entrypoint: ["/entrypoint.sh"]
