[tool.ruff]
line-length = 88
lint.select = ["E", "F", "I"]  
lint.ignore = ["E501"]         

[tool.ruff.lint.isort]  
combine-as-imports = true
force-single-line = false
known-first-party = ["fuel_project", "fuel_route_api"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]






