# Generated by Django 5.2 on 2025-07-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel_route_api", "0002_remove_fuelstation_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelstation",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuelstation",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
