# Generated by Django 5.2.4 on 2025-07-28 02:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fuel_route_api", "0003_fuelstation_latitude_fuelstation_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuelstation",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="fuelstation",
            name="longitude",
        ),
        migrations.AddField(
            model_name="fuelstation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
